[WIP] Feature/setup scope validator core
CourseDesign/scope-validator pull request #1
Opened 2020-09-13 17:38 UTC by Su-Yong

## 관련 이슈
scope validation을 위한 validator 필요

## 현재 상황
ScopeValidatorCore 작업 완료

## 개선 방법
소스 참고

## 예상 되는 부수 효과
* 스코프 스타일을 마음대로 변경할 수 있음
* optional 비교를 보다 free하게 할수 있음 (작업 예정)

## TODO
- [ O ] 테스트 코드 작성
- [ O ] 비즈니스 로직 작성
- [ O ] 로컬 환경에서 테스트

## Reference
없음

2020-09-13 23:52 UTC, siyual-park commented on .eslintignore
> +jest.config.js
\n

2020-09-13 23:52 UTC, siyual-park commented on .eslintrc.json
> -  "parser": "@typescript-eslint/parser",
이걸 뺸 이유는 뭔가요?

2020-09-13 23:52 UTC, siyual-park commented on packages/scope-validator-core/lib/scope/scope-validator.ts
> +  validate(name: string): Result<void> {
validate 에 성공한 scope 를 리턴하면 좋을거 같아요

2020-09-13 23:52 UTC, siyual-park commented on packages/scope-validator-core/lib/scope/scope.ts
> +/*
필요 없는 주석은 삭제 (참고 코드는 깃헙 위키나 노션이나 다른 곳에 넣어주세요)

2020-09-13 23:52 UTC, siyual-park commented on packages/scope-validator-core/lib/shape/divider.ts
> +export default {
한번 레핑힐 필요는 없는거 같아요 default 바로 export 하면 더 직관적일거 같아요

2020-09-14 00:00 UTC, siyual-park requested changes

2020-09-14 00:00 UTC, siyul-park commented on packages/scope-validator-core/lib/scope/scope-builder.ts
> +export default {
바로 default로 export?

2020-09-14 00:00 UTC, siyul-park commented on packages/scope-validator-core/lib/scope/scope-builder.ts
> +/*
주석 지우기

2020-09-14 00:00 UTC, siyul-park commented on packages/scope-validator-core/lib/scope/scope-shape.ts
> +    this.divider = divider;
option을 저장하는것 확장성이 좋을거 같아요

2020-09-14 00:00 UTC, siyul-park commented on packages/scope-validator-core/lib/scope/scope-validator.ts
> +    const results: Result<void>[] = this.scopeShape.shapes.map(
굳이 ok, error 같은 Result 타입을 운용하는데 이점이 있나 생각이 들어요.

2020-09-14 00:11 UTC, siyual-park requested changes

2020-09-14 00:11 UTC, siyual-park commented on packages/scope-validator-core/lib/scope/scope-shape.ts
> +export default {
바로 export

2020-09-14 00:11 UTC, siyual-park commented on packages/scope-validator-core/lib/scope/scope.ts
> +export default {
바로 export

2020-09-14 00:11 UTC, siyual-park commented on packages/scope-validator-core/lib/scope/scope-builder.ts
> +export class ScopeBuilder<T extends ScopeShape> {
builder 인데 빌더 패턴이 아닌듯 해요.
이건 그냥 팩토리로 보이네요

2020-09-14 00:11 UTC, siyual-park commented on packages/scope-validator-core/lib/scope/scope-validator.ts
> +  validate(name: string): Result<void> {
name 만으로 모든 경우를 확인할수는 없을거 같아요. 좀더 추상화 부탁드릴게요.
지금의 scope 시스템에 너무 의존적인거 같네요

2020-09-14 00:11 UTC, siyual-park commented on packages/scope-validator-core/lib/test/integration/validator.spec.ts
> +    const result = scope.validate();
지금 name 으로만 validate 가 가능한데 근본적으로 문제가 있는거 같아요.
현재 상태에 따라서 유동적으로 validate가 되는게 맞을거 같네요

2020-09-14 08:57 UTC, 5d-jh commented on packages/scope-validator-core/lib/shape/variable-shape.ts
> +    const shapeValidator = validator ?? new VariableShapeValidator();
파라미터에 기본값을 지정하는게 더 깔끔해 보일 것 같아요

2020-09-14 08:58 UTC, Su-Yong commented on packages/scope-validator-core/lib/shape/variable-shape.ts
> +    const shapeValidator = validator ?? new VariableShapeValidator();
초기에 ShapeValidator의 인자에 shape인 this가 들어가게 헀다가 제대로 작동을안해서 뺐는데 까먹고 default로 지정안한거 같네요 일단 이부분이 남아있으면... 수정하겠습니다

2020-09-14 09:00 UTC, 5d-jh commented on packages/scope-validator-core/lib/scope/scope-validator.ts
> +      return ERROR('Shape length is longer than expected');
ERROR라는 결과값을 주기보단 throw 하는게 더 나을 것 같아요

2020-09-14 09:03 UTC, Su-Yong commented on packages/scope-validator-core/lib/scope/scope-validator.ts
> +      return ERROR('Shape length is longer than expected');
내부적으로 Result 타입을 사용한후에 외부로 보여질때 에러를 throw하는게 더 좋아보여서 이렇게 했어요
아니면 내부적으로 Error를 return하는 방식을 사용하는게 좋을까요?

2020-09-14 09:06 UTC, 5d-jh commented on packages/scope-validator-core/lib/scope/scope-validator.ts
> +      return ERROR('Shape length is longer than expected');
try/catch 문을 사용하지 않으면 외부로 바로 throw 되지 않나요? 전 오류가 생기는 지점과 가장 가까운 지점에서 throw를 하는게 더 보기 좋다고 생각해요

2020-09-14 09:08 UTC, Su-Yong commented on packages/scope-validator-core/lib/scope/scope-validator.ts
> +      return ERROR('Shape length is longer than expected');
확인했습니다 그렇게 바꿔보겠습니다

2020-09-14 13:01 UTC, Su-Yong commented on packages/scope-validator-core/lib/scope/scope-validator.ts
> +  validate(name: string): Result<void> {
name 만으로 모든경우를 확인할수 없다는게 구체적으로 어떤지 예시를 들어주시면 좋겠습니다

2020-09-14 13:09 UTC, siyual-park commented on packages/scope-validator-core/lib/scope/scope-validator.ts
> +  validate(name: string): Result<void> {
read:user:me

같은 scope가 있다고 보고

호출하는 user 의 id 가 1이라고 보죠.

id가 1 인 user 가 id가 2인 리소스에 접근 할때도 발리데이션은 성공하고

id 가 1인 리소스에 접근해도 발리데이션은 성공할 겁니다

2020-09-14 13:23 UTC, siyual-park requested changes

2020-09-14 13:23 UTC, siyual-park commented on packages/scope-validator-core/lib/shape/shape.ts
> +  validator: ShapeValidator;
ShapeValidator 에서 shape 를 참조하고 shape 에서 validator 를 참조 하는거 같아요

2020-09-14 13:32 UTC, closed without merging