Feature/scope validator
CourseDesign/scope-validator pull request #2
Opened 2020-09-15 10:20 UTC by Su-Yong

## 관련 이슈
scope validation을 위한 validator 필요

## 현재 상황
ScopeValidator 작업 완료

## 개선 방법
소스 참고

## 예상 되는 부수 효과
* 탬플릿 string과 같은 방식을 통해 파라미터를 가져오기 쉬움
* 해당 스코프와 매치되는 모든 validator가 validate해야 제대로된 validation으로 인식됨

## TODO
- [X] 테스트 코드 작성
- [X] 비즈니스 로직 작성
- [X] 로컬 환경에서 테스트

## Reference

2020-09-15 11:12 UTC, siyual-park requested changes

2020-09-15 11:12 UTC, siyul-park commented on packages/scope-validator-core/lib/scope.ts
> +export default class Scope {}
이건 어디에서 사용이 되나요?

2020-09-15 11:12 UTC, siyual-park commented on packages/scope-validator-core/lib/scope-validator-manager.ts
> +  validate(...scopes: string[]): boolean[] {
validate 시에 context(recived) 를 넘길수 있으면 좋을거 같아요 context가 mapper에 의존적인것 보다는 validate 호출 시점에 같이 넘어가는것이 자연스러울거 같에요

2020-09-15 11:12 UTC, siyual-park commented on packages/scope-validator-core/lib/scope-validator-context.ts
> +  received?: Record<string, unknown>;
확장 가능하게 템플릿으로 제공하면 좋을거 같아요

2020-09-15 11:12 UTC, siyual-park commented on packages/scope-validator-core/lib/scope-validator-manager.ts
> +  scopeValidators: ScopeValidator[] = [];
private readonly

2020-09-15 11:12 UTC, siyual-park commented on packages/scope-validator-core/lib/scope-validator-manager.ts
> +  context: Record<string, unknown> = {};
ditto

2020-09-15 11:12 UTC, siyual-park commented on packages/scope-validator-core/test/index.spec.ts
> +    scopeValidatorManager.context = {
validator manager 은 class 인데 struct의 역활도 혼용하는거 같아서 맴버 변수는 전부 private으로 바꾸는게 좋을거 같아요

2020-09-16 02:58 UTC, Su-Yong commented on packages/scope-validator-core/lib/scope-validator-context.ts
> +  received?: Record<string, unknown>;
received가 일단은 [key: string]: unknown 타입이여서 일반적인 객체는 통과할것 처럼 보이는데 더 확장가능할게 있을까요?

2020-09-16 04:36 UTC, siyual-park commented on packages/scope-validator-core/lib/scope-validator-context.ts
> +  received?: Record<string, unknown>;
템플릿으로 자유롭게 타입을 설정하면 좋을거 같아요

2020-09-16 07:22 UTC, angello10 approved these changes

2020-09-16 08:46 UTC, siyual-park requested changes

2020-09-16 08:46 UTC, siyual-park commented on packages/scope-validator-core/lib/scope-validator-factory.ts
> +      validate(name: string, context: ScopeValidatorContext<T>) {
리턴 타입 누락됬어요

2020-09-16 08:46 UTC, Su-Yong commented on packages/scope-validator-core/lib/scope-validator-context.ts
> +  received?: Record<string, unknown>;
새 커밋에 반영되었습니다 감사합니다

2020-09-16 08:55 UTC, Su-Yong commented on packages/scope-validator-core/lib/scope-validator-factory.ts
> +      validate(name: string, context: ScopeValidatorContext<T>) {
수정되었습니다

2020-09-16 09:19 UTC, merged